export const dataProjects = [
  {
    descripcion: "",
    img: "/img/perf-mundial.png",
    alt: "",
    tecnologias: [
      "React",
      "Mongo",
      "Mercado Pago API",
      "Node",
      "Styled-components",
    ],
    titulo: "",
    github: "",
    web: "https://www.perfumeriamundial.ar/",
  },
  {
    descripcion: "",
    img: "/img/typescript-react.png",
    alt: "",
    tecnologias: ["React", "Typescript", "JWT", "Node", "Styled-components"],
    titulo: "",
    github: "https://github.com/CarelessAsado/Typescript-React-firstApp",
    web: "https://amazing-wright-70ac6b.netlify.app/",
  },
  {
    descripcion: "",
    img: "/img/Portfolio.png",
    alt: "",
    tecnologias: ["React", "Intersection Observer", "i18n", "PostgreSQL"],
    titulo: "",
    github: "https://github.com/CarelessAsado/PORTFOLIO-TRANSLATED-INTO-REACT",
    web: "https://www.rodrigohernanlopez.com.ar/",
  },
  {
    descripcion: "",
    img: "/img/React+JWT.png",
    alt: "",
    tecnologias: ["React", "Nodejs", "JWT", "Mongoose"],
    titulo: "PROYECTO MERN",
    github: "https://github.com/CarelessAsado/MERN-TaskManagement",
    web: "https://frosty-archimedes-bb3dfe.netlify.app/",
  },
  {
    descripcion:
      "Recreación del famoso sitio. Previo registro e inicio de sesión, los usuarios pueden acceder a un muro público para escribir mensajes, así como acceder de manera privada a su información de usuario y editarla.",
    img: "/img/rodribook.png",
    alt: "proyecto Rodribook",
    tecnologias: ["Nodejs", "Express-sessions", "MongoDb", "Mongoose"],
    titulo: "RODRIBOOK WEBSITE",
    github: "https://github.com/CarelessAsado/rodribook",
    web: "",
  },
  {
    descripcion:
      "Juego de blackjack que tomé como base del sitio Free Code Camp, y que luego fui adaptando: notificaciones sobre el estado de la partida, un bot dealer, interfaz para realizar apuestas, etc.",
    img: "/img/blackjack.png",
    alt: "proyecto Blackjack",
    tecnologias: ["Javascript", "HTML", "CSS"],
    titulo: "BLACKJACK GAME",
    github: "https://github.com/CarelessAsado/jackblack",
    web: "https://carelessasado.github.io/jackblack/",
  },
  {
    descripcion: "Mi primer sitio web.",
    img: "/img/rohelaw.com.ar.png",
    alt: "proyecto Rohelaw",
    tecnologias: ["Javascript", "HTML", "CSS"],
    titulo: "ROHELAW WEBSITE",
    github: "https://github.com/CarelessAsado/sworntranslation_site",
    web: "http://rohelaw.com.ar/",
  },
];
